<?php
/**
 * Template: Bloque 4 — Corporativo
 * @package Romvill
 */
require_once get_template_directory() . '/inc/questionnaire-engine.php';

$config = array(
    'block'         => 4,
    'profile_name'  => 'Corporativo',
    'profile_ref'   => 'BLOQUE 4',
    'page_title'    => 'Solicitar Presupuesto — Corporativo — ROMVILL',
    'page_desc'     => 'Cuestionario corporativo: estudio de viabilidad, expansión, demografía empresarial, competencia.',
    'logo_sub'      => 'Análisis de Inteligencia Zonal · Corporativo',
    'storage'       => array( 'answers' => 'romvill_b4_ans', 'lang' => 'romvill_b4_lang' ),
    'prioritySections' => array(
        array( 'n' => 'Demografía y poder adquisitivo del entorno', 'l' => 'hi' ),
        array( 'n' => 'Análisis de competencia local',              'l' => 'hi' ),
        array( 'n' => 'Tráfico y flujos peatonales',                'l' => 'hi' ),
        array( 'n' => 'Disponibilidad inmobiliaria comercial',      'l' => 'hi' ),
        array( 'n' => 'Conectividad y accesos',                     'l' => 'hi' ),
        array( 'n' => 'Marco regulatorio y licencias de actividad', 'l' => 'hi' ),
        array( 'n' => 'Talento profesional disponible',             'l' => 'md' ),
        array( 'n' => 'Idiomas hablados en la zona',                'l' => 'md' ),
        array( 'n' => 'Comunidad internacional y expatriados',      'l' => 'md' ),
        array( 'n' => 'Eventos y dinamismo local',                  'l' => 'md' ),
        array( 'n' => 'Tendencias de consumo en la zona',           'l' => 'md' ),
        array( 'n' => 'Infraestructura digital y conectividad',     'l' => 'md' ),
        array( 'n' => 'Estacionalidad y patrones turísticos',       'l' => 'md' ),
        array( 'n' => 'Costes operativos en la zona',               'l' => 'md' ),
        array( 'n' => 'Marco fiscal local',                         'l' => 'md' ),
        array( 'n' => 'Imagen y posicionamiento de la zona',        'l' => 'lo' ),
        array( 'n' => 'Vida cultural y ocio',                       'l' => 'lo' ),
    ),
    'lang' => array(
        'es' => array(
            'time'      => 'Aproximadamente 5 minutos',
            'btn'       => 'EMPEZAMOS',
            'logoSub'   => 'Análisis de Inteligencia Zonal · Corporativo',
            'coverTag'  => 'BLOQUE 4 — CORPORATIVO',
            'coverTitle'=> 'Solicitar Presupuesto',
            'coverDoc'  => 'Cuestionario corporativo · Análisis de Inteligencia Zonal',
            'cvp1'      => 'Las decisiones empresariales sobre apertura, expansión o reubicación exigen datos rigurosos y específicos del sector. Las siguientes preguntas nos permitirán adaptar el alcance del análisis a su <strong>actividad concreta</strong>, sus criterios de éxito y sus plazos.',
            'cvp2'      => 'Trabajamos con la confidencialidad y la objetividad que demandan las decisiones corporativas estratégicas.',
            'cvp3'      => 'El criterio empresarial antes de decidir, en las mejores manos.',
            'cvdisc'    => '<strong>ROMVILL no comercializa inmuebles, no cobra comisiones y no representa a ningún operador.</strong> Nuestro análisis es independiente y, si lo requiere, podemos firmar NDA. Sus datos corporativos son tratados con máxima confidencialidad.',
            'midTitle'  => 'Gracias por completar el cuestionario.',
            'midP1'     => 'Con la información facilitada elaboraremos un presupuesto adaptado a su proyecto empresarial.',
            'midP2'     => 'Una vez aceptado, comenzaremos el Análisis de Inteligencia Zonal con un equipo dedicado y entregables compatibles con su proceso interno (informe + presentación ejecutiva).',
            'midBtn'    => 'Ver mi perfil',
            'sendTitle' => '¿Todo correcto?',
            'sendSub'   => 'Revise su perfil corporativo y envíe la solicitud. Recibirá un presupuesto personalizado en un plazo de 24-48 horas laborables.',
            'agentTitle'=> 'Solicito interlocutor único senior',
            'agentSub'  => 'Asignaremos un analista senior como punto de contacto único, con disponibilidad para coordinar con su equipo directivo.',
            'blocks'    => (object) array(
                '1' => 'Sobre la empresa',
                '7' => 'El proyecto empresarial',
                '11'=> 'Requisitos del análisis',
                '14'=> 'Plazos y entrega',
            ),
            'motivators' => (object) array(
                '7'  => array( 'txt' => 'EMPRESA REGISTRADA',     'sub' => 'Pasamos al proyecto' ),
                '11' => array( 'txt' => 'PROYECTO DEFINIDO',      'sub' => 'Vamos a los requisitos del análisis' ),
                '14' => array( 'txt' => 'CASI LISTO',             'sub' => 'Solo plazos y formato de entrega' ),
            ),
            'questions' => array(
                array(
                    'text' => 'Datos del responsable del proyecto',
                    'note' => 'Persona que actuará como interlocutor con ROMVILL durante la elaboración del análisis.',
                    'type' => 'cmp', 'req' => true,
                    'fields' => array(
                        array( 'id' => 'nt',     'lbl' => 'Nombre completo', 'type' => 'text', 'ph' => 'Nombre y apellidos', 'req' => true ),
                        array( 'id' => 'cargo',  'lbl' => 'Cargo en la empresa', 'type' => 'text', 'ph' => 'Director, CEO, Responsable…', 'req' => true ),
                    ),
                    'profileLabel' => 'Responsable del proyecto', 'profileFull' => true,
                ),
                array(
                    'text' => 'Nombre de la empresa o entidad',
                    'type' => 'text', 'key' => 'empresa', 'ph' => 'Razón social de la empresa', 'req' => true,
                    'profileLabel' => 'Empresa', 'profileLg' => true,
                ),
                array(
                    'text' => '¿Cuál es el sector principal de actividad de su empresa?',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Retail / comercio minorista',
                        'Hostelería y restauración',
                        'Servicios profesionales (consultoría, legal, ingeniería)',
                        'Salud, bienestar y wellness',
                        'Educación y formación',
                        'Tecnología, digital e innovación',
                        'Inmobiliario y servicios afines',
                        'Industrial, manufactura y logística',
                        'Cultura, ocio, deportes y entretenimiento',
                        'Servicios financieros y banca',
                        'Otro sector',
                    ),
                    'profileLabel' => 'Sector de actividad', 'profileFull' => true,
                ),
                array(
                    'text' => '¿En qué país tiene su sede principal?',
                    'type' => 'text', 'key' => 'sede', 'ph' => 'País de la sede principal', 'req' => true,
                    'profileLabel' => 'Sede principal',
                ),
                array(
                    'text' => 'Correo electrónico corporativo de contacto',
                    'note' => 'Le enviaremos el presupuesto a este correo. Si necesita copia a varias personas, indíquelo en los comentarios finales.',
                    'type' => 'text', 'key' => 'email', 'input' => 'email', 'ph' => 'contacto@empresa.com', 'req' => true,
                    'profileLabel' => 'Email corporativo', 'profileLg' => true,
                ),
                array(
                    'text' => 'Teléfono de contacto',
                    'note' => 'Solo para coordinaciones rápidas. Trato confidencial.',
                    'type' => 'tel', 'req' => false, 'optional' => true,
                ),
                array(
                    'text' => '¿En qué idioma desea recibir el informe?',
                    'type' => 'single', 'req' => true,
                    'opts' => array( 'Español', 'English', 'Deutsch', 'Français', 'Português', 'Русский', 'Bilingüe (ES + EN)' ),
                    'profileLabel' => 'Idioma del informe', 'profileLg' => true,
                ),
                array(
                    'text' => '¿Qué tipo de análisis necesita?',
                    'note' => 'Si su caso combina varios objetivos, escoja el principal e indique los demás en los comentarios finales.',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Estudio de viabilidad para apertura de nueva localización',
                        'Análisis comparativo entre varias zonas candidatas',
                        'Estudio de mercado y competencia en la zona',
                        'Análisis para reubicación de oficinas / instalaciones',
                        'Estudio para expansión de red existente',
                        'Análisis para evento / proyecto puntual',
                        'Diagnóstico estratégico de la zona para mi sector',
                        'Otro tipo de análisis',
                    ),
                    'profileLabel' => 'Tipo de análisis', 'profileFull' => true,
                ),
                array(
                    'text' => '¿En qué zona o ciudad necesita el análisis?',
                    'type' => 'zona', 'req' => true,
                    'opts' => array( 'Marbella · Costa del Sol', 'Málaga', 'Alicante · Costa Blanca', 'Otra zona / Otro país' ),
                    'profileLabel' => 'Zona del análisis', 'profileLg' => true,
                ),
                array(
                    'text' => '¿Cuántas localizaciones está considerando o tiene en operación?',
                    'note' => 'El número de localizaciones nos permite calibrar el alcance comparativo del análisis.',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Una primera localización (apertura única)',
                        'Una nueva localización entre 2-5 ya existentes',
                        'Una nueva localización entre más de 5 ya existentes',
                        '2-5 aperturas simultáneas planificadas',
                        'Más de 5 aperturas simultáneas planificadas',
                        'Análisis estratégico — sin localización concreta aún',
                    ),
                    'profileLabel' => 'Número de localizaciones',
                ),
                array(
                    'text' => '¿Qué dimensión prevé en la nueva ubicación?',
                    'note' => 'Indique el rango aproximado de plantilla esperada. Puede actualizarse durante el análisis.',
                    'type' => 'single', 'req' => false, 'optional' => true,
                    'opts' => array(
                        'Menos de 5 empleados',
                        '5 a 20 empleados',
                        '20 a 50 empleados',
                        '50 a 200 empleados',
                        'Más de 200 empleados',
                        'Por determinar',
                    ),
                    'profileLabel' => 'Dimensión prevista',
                ),
                array(
                    'text' => '¿Qué información empresarial es prioritaria en su análisis?',
                    'note' => 'Marcamos los focos prioritarios para profundizar más en los aspectos relevantes para su decisión.',
                    'type' => 'multi', 'req' => true,
                    'opts' => array(
                        'Demografía y poder adquisitivo del entorno',
                        'Competencia local directa e indirecta',
                        'Tráfico y flujos peatonales / vehiculares',
                        'Disponibilidad inmobiliaria comercial',
                        'Conectividad y accesos (logística)',
                        'Marco regulatorio y licencias',
                        'Talento profesional disponible en la zona',
                        'Idiomas hablados en la zona',
                        'Comunidad internacional y expatriados',
                        'Eventos y dinamismo local',
                        'Tendencias de consumo y comportamiento',
                        'Infraestructura digital',
                        'Estacionalidad turística',
                        'Otros aspectos',
                    ),
                    'profileLabel' => 'Información empresarial prioritaria', 'profileFull' => true,
                ),
                array(
                    'text' => '¿A qué público objetivo orienta su negocio?',
                    'note' => 'Esto nos permite calibrar el análisis demográfico y de mercado al perfil de su cliente.',
                    'type' => 'multi', 'req' => false, 'optional' => true,
                    'opts' => array(
                        'Cliente nacional residente',
                        'Cliente internacional / turista',
                        'Comunidad expatriada residente',
                        'Empresas (B2B)',
                        'Sector público / administraciones',
                        'Premium / lujo',
                        'Generalista / mass-market',
                        'Otros',
                    ),
                    'profileLabel' => 'Público objetivo', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Tiene una propiedad o local concreto en estudio?',
                    'note' => 'Si tiene opciones identificadas indíquenoslo brevemente. Si no, identificaremos la zona óptima.',
                    'type' => 'swf', 'req' => false, 'optional' => true,
                    'opts' => array(
                        array( 'lbl' => 'Sí, tengo una propiedad/local concreto en estudio', 'hasF' => true,  'fph' => 'Dirección, referencia o enlace al anuncio' ),
                        array( 'lbl' => 'Sí, tengo varias opciones que evaluar',              'hasF' => true,  'fph' => 'Indique brevemente las opciones que está valorando' ),
                        array( 'lbl' => 'No, primero necesito identificar la mejor zona',     'hasF' => false ),
                    ),
                    'profileLabel' => 'Propiedad/local en estudio', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cuál es el plazo estimado del proyecto de apertura/expansión?',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Inminente — próximos 1-3 meses',
                        'Corto plazo — 3-6 meses',
                        'Medio plazo — 6-12 meses',
                        'Largo plazo — más de 12 meses',
                        'Aún en fase exploratoria',
                    ),
                    'profileLabel' => 'Plazo del proyecto',
                ),
                array(
                    'text' => '¿Qué formato de entrega del informe necesita?',
                    'note' => 'Adaptamos los entregables a su proceso interno (comité, dirección, equipo).',
                    'type' => 'multi', 'req' => false, 'optional' => true,
                    'opts' => array(
                        'Informe ejecutivo (PDF)',
                        'Presentación a comité directivo (PowerPoint)',
                        'Datos exportables (Excel, CSV)',
                        'Sesión de presentación / reunión con su equipo',
                        'Informe en idiomas adicionales',
                        'Acuerdo de confidencialidad (NDA) requerido',
                        'Mapeo cartográfico georreferenciado',
                    ),
                    'profileLabel' => 'Formato de entrega', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cómo prefiere recibir el presupuesto?',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Por correo electrónico',
                        'Correo + videollamada para presentación ejecutiva',
                        'Reunión presencial en Marbella / Málaga / Alicante',
                        'Reunión presencial en su sede',
                    ),
                    'profileLabel' => 'Preferencia de entrega del presupuesto',
                ),
                array(
                    'text' => '¿Cómo nos ha conocido?',
                    'type' => 'single', 'req' => false, 'optional' => true,
                    'opts' => array(
                        'Búsqueda en Google',
                        'Recomendación profesional (consultor, abogado, gestor)',
                        'Recomendación personal',
                        'Redes sociales / LinkedIn',
                        'Eventos / conferencias',
                        'Otro canal',
                    ),
                    'profileLabel' => 'Canal de origen',
                ),
                array(
                    'text' => 'Información corporativa adicional que considere relevante',
                    'note' => 'Cualquier sensibilidad estratégica, requisito interno o expectativa específica que deba conocer ROMVILL.',
                    'type' => 'textarea', 'key' => 'q19', 'ph' => 'Comentarios e información adicional...', 'req' => false, 'optional' => true,
                    'profileLabel' => 'Información adicional', 'profileFull' => true,
                ),
            ),
        ),
    ),
);

foreach ( array( 'en', 'de', 'fr', 'pt', 'ru' ) as $l ) {
    $config['lang'][ $l ] = $config['lang']['es'];
}

romvill_q_render( $config );
