<?php
/**
 * Template: Bloque 3 — Gran Inversor / Promotor
 * @package Romvill
 */
require_once get_template_directory() . '/inc/questionnaire-engine.php';

$config = array(
    'block'         => 3,
    'profile_name'  => 'Gran Inversor / Promotor',
    'profile_ref'   => 'BLOQUE 3',
    'page_title'    => 'Solicitar Presupuesto — Gran Inversor / Promotor — ROMVILL',
    'page_desc'     => 'Cuestionario para grandes inversores y promotores: proyectos, urbanismo, magnitud, stakeholders.',
    'logo_sub'      => 'Análisis de Inteligencia Zonal · Gran Inversor / Promotor',
    'storage'       => array( 'answers' => 'romvill_b3_ans', 'lang' => 'romvill_b3_lang' ),
    'prioritySections' => array(
        array( 'n' => 'Marco urbanístico y planeamiento',         'l' => 'hi' ),
        array( 'n' => 'Permisos y licencias requeridas',          'l' => 'hi' ),
        array( 'n' => 'Análisis de demanda y mercado objetivo',   'l' => 'hi' ),
        array( 'n' => 'Estudio de viabilidad económica',          'l' => 'hi' ),
        array( 'n' => 'Análisis de competencia y proyectos similares', 'l' => 'hi' ),
        array( 'n' => 'Conectividad e infraestructuras',          'l' => 'hi' ),
        array( 'n' => 'Marco fiscal y legal específico',          'l' => 'hi' ),
        array( 'n' => 'Impacto ambiental y normativa',            'l' => 'md' ),
        array( 'n' => 'Contexto sociodemográfico',                'l' => 'md' ),
        array( 'n' => 'Tendencias del sector y previsiones',      'l' => 'md' ),
        array( 'n' => 'Riesgos políticos y regulatorios',         'l' => 'md' ),
        array( 'n' => 'Acceso a financiación local',              'l' => 'md' ),
        array( 'n' => 'Capacidad de suministro / proveedores',    'l' => 'md' ),
        array( 'n' => 'Talento y mano de obra disponible',        'l' => 'md' ),
        array( 'n' => 'Comunidades internacionales y expatriados','l' => 'md' ),
        array( 'n' => 'Servicios de lujo y oferta complementaria','l' => 'lo' ),
        array( 'n' => 'Indicadores macroeconómicos',              'l' => 'lo' ),
    ),
    'lang' => array(
        'es' => array(
            'time'      => 'Aproximadamente 6 minutos',
            'btn'       => 'EMPEZAMOS',
            'logoSub'   => 'Análisis de Inteligencia Zonal · Gran Inversor / Promotor',
            'coverTag'  => 'BLOQUE 3 — GRAN INVERSOR / PROMOTOR',
            'coverTitle'=> 'Solicitar Presupuesto',
            'coverDoc'  => 'Cuestionario para grandes inversores y promotores · Análisis de Inteligencia Zonal',
            'cvp1'      => 'Los proyectos de gran escala requieren un análisis estratégico, riguroso y multidisciplinar. Las siguientes preguntas nos permitirán dimensionar adecuadamente el alcance de su <strong>Análisis de Inteligencia Zonal</strong> y elaborar un presupuesto a la medida del proyecto.',
            'cvp2'      => 'Trabajamos con la confidencialidad y el rigor que su nivel de decisión exige.',
            'cvp3'      => 'Su criterio antes de decidir, en las mejores manos.',
            'cvdisc'    => '<strong>ROMVILL no vende inmuebles, no cobra comisiones y no tiene ningún interés en su decisión.</strong> Operamos con total independencia y, si lo requiere, bajo NDA. Sus datos son tratados con máxima confidencialidad.',
            'midTitle'  => 'Gracias por completar el cuestionario.',
            'midP1'     => 'Con la información facilitada elaboraremos un presupuesto adaptado a la magnitud y complejidad de su proyecto.',
            'midP2'     => 'Una vez aceptado, comenzaremos el Análisis de Inteligencia Zonal con un equipo dedicado y entrega en el formato que necesite.',
            'midBtn'    => 'Ver mi perfil',
            'sendTitle' => '¿Todo correcto?',
            'sendSub'   => 'Revise su perfil y envíe la solicitud. Recibirá un presupuesto personalizado en un plazo de 24-48 horas laborables.',
            'agentTitle'=> 'Solicito gestor dedicado para mi proyecto',
            'agentSub'  => 'Asignaremos un analista senior como punto de contacto único durante todo el proceso.',
            'blocks'    => (object) array(
                '1' => 'Sobre usted o la entidad',
                '7' => 'Naturaleza del proyecto',
                '10'=> 'Magnitud y requerimientos',
                '13'=> 'Stakeholders y gobernanza',
                '15'=> 'Plazos y entrega',
            ),
            'motivators' => (object) array(
                '7'  => array( 'txt' => 'PERFIL REGISTRADO',     'sub' => 'Pasamos al proyecto' ),
                '10' => array( 'txt' => 'PROYECTO DEFINIDO',     'sub' => 'Vamos al dimensionamiento' ),
                '15' => array( 'txt' => 'CASI LISTO',            'sub' => 'Solo plazos y entrega' ),
            ),
            'questions' => array(
                array(
                    'text' => 'Datos del decisor / interlocutor principal',
                    'note' => 'Datos del responsable del proyecto que actuará como interlocutor con ROMVILL.',
                    'type' => 'cmp', 'req' => true,
                    'fields' => array(
                        array( 'id' => 'nt',     'lbl' => 'Nombre completo',              'type' => 'text', 'ph' => 'Nombre y apellidos', 'req' => true ),
                        array( 'id' => 'cargo',  'lbl' => 'Cargo / función en el proyecto','type' => 'text', 'ph' => 'CEO, Director, Socio…', 'req' => true ),
                    ),
                    'profileLabel' => 'Decisor / Interlocutor', 'profileFull' => true,
                ),
                array(
                    'text' => 'Empresa, sociedad o vehículo inversor',
                    'note' => 'Si la inversión se realiza a través de una sociedad o vehículo, indíquenos su nombre. Si es inversión personal, déjelo en blanco o indique "Personal".',
                    'type' => 'text', 'key' => 'empresa', 'ph' => 'Razón social del vehículo inversor', 'req' => false, 'optional' => true,
                    'profileLabel' => 'Vehículo inversor',
                ),
                array(
                    'text' => '¿En qué país tiene su sede principal o residencia fiscal?',
                    'type' => 'text', 'key' => 'fiscal', 'ph' => 'País de la sede o residencia fiscal', 'req' => true,
                    'profileLabel' => 'Sede / residencia fiscal',
                ),
                array(
                    'text' => '¿Cuál es su correo electrónico de contacto?',
                    'note' => 'Le enviaremos el presupuesto a este correo. Si requiere copia a varias personas, indíquelo en los comentarios finales.',
                    'type' => 'text', 'key' => 'email', 'input' => 'email', 'ph' => 'correo@empresa.com', 'req' => true,
                    'profileLabel' => 'Email de contacto', 'profileLg' => true,
                ),
                array(
                    'text' => 'Número de contacto directo',
                    'note' => 'Para coordinaciones rápidas. Trato confidencial.',
                    'type' => 'tel', 'req' => false, 'optional' => true,
                ),
                array(
                    'text' => '¿En qué idioma desea recibir el análisis?',
                    'type' => 'single', 'req' => true,
                    'opts' => array( 'Español', 'English', 'Deutsch', 'Français', 'Português', 'Русский', 'Multilingüe (varios idiomas)' ),
                    'profileLabel' => 'Idioma del informe', 'profileLg' => true,
                ),
                array(
                    'text' => '¿Qué tipo de proyecto está considerando?',
                    'note' => 'Identifíquelo lo más precisamente posible. Si es híbrido, escoja la categoría dominante.',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Promoción residencial (urbanización, complejo, edificio)',
                        'Promoción mixta (residencial + comercial)',
                        'Proyecto hotelero / turístico / resort',
                        'Centro comercial / oficinas / coworking',
                        'Industrial / logístico / data center',
                        'Reconversión / regeneración urbana',
                        'Adquisición de suelo para futura promoción',
                        'Adquisición estratégica (cartera, edificio único, joya patrimonial)',
                        'Inversión en activos rentables (build-to-rent, BTR)',
                        'Otro tipo de proyecto',
                    ),
                    'profileLabel' => 'Tipo de proyecto', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cuál es la ubicación principal del proyecto?',
                    'type' => 'zona', 'req' => true,
                    'opts' => array( 'Marbella · Costa del Sol', 'Málaga', 'Alicante · Costa Blanca', 'Otra zona / Otro país' ),
                    'profileLabel' => 'Ubicación del proyecto', 'profileLg' => true,
                ),
                array(
                    'text' => '¿En qué fase se encuentra actualmente el proyecto?',
                    'note' => 'La fase actual determina la profundidad y el enfoque del análisis necesario.',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Estudio preliminar — buscando oportunidades',
                        'Oportunidad identificada — evaluándola',
                        'Contacto avanzado con propietario / promotor',
                        'En proceso de adquisición / negociación',
                        'Adquirido — fase de planificación',
                        'En desarrollo — necesito información complementaria',
                    ),
                    'profileLabel' => 'Fase del proyecto', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cuál es la superficie aproximada del terreno o proyecto?',
                    'note' => 'Si manejas varias hipótesis indique la superficie objetivo principal.',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Menos de 5.000 m²',
                        'Entre 5.000 y 20.000 m²',
                        'Entre 20.000 y 100.000 m²',
                        'Entre 100.000 y 500.000 m²',
                        'Más de 500.000 m²',
                        'Aún por definir',
                    ),
                    'profileLabel' => 'Superficie del proyecto',
                ),
                array(
                    'text' => '¿Cuál es el rango de inversión estimado para el proyecto?',
                    'note' => 'Indique el rango global del proyecto (adquisición + desarrollo si procede).',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Hasta 5 M€',
                        'Entre 5 M€ y 20 M€',
                        'Entre 20 M€ y 50 M€',
                        'Entre 50 M€ y 200 M€',
                        'Más de 200 M€',
                        'Confidencial — prefiero no indicarlo',
                    ),
                    'profileLabel' => 'Rango de inversión',
                ),
                array(
                    'text' => '¿Qué aspectos son críticos para su decisión?',
                    'note' => 'Seleccione los focos prioritarios. El análisis se calibrará para cubrir con mayor profundidad los aspectos marcados.',
                    'type' => 'multi', 'req' => true,
                    'opts' => array(
                        'Marco urbanístico y planeamiento vigente',
                        'Permisos, licencias y plazos administrativos',
                        'Análisis de demanda y mercado objetivo',
                        'Estudio de viabilidad económica completo',
                        'Análisis de competencia y proyectos similares',
                        'Análisis de impacto ambiental y normativa',
                        'Contexto sociodemográfico de la zona',
                        'Conectividad e infraestructuras',
                        'Marco fiscal y legal específico',
                        'Riesgos políticos y regulatorios',
                        'Acceso a financiación local',
                        'Otros aspectos críticos',
                    ),
                    'profileLabel' => 'Aspectos críticos', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cuál es la estructura de participación en el proyecto?',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Inversión propia individual',
                        'Sociedad familiar / vehículo propio',
                        'Joint venture con socio local español',
                        'Joint venture con socio internacional',
                        'Fondo de inversión institucional',
                        'En proceso de búsqueda de socios',
                    ),
                    'profileLabel' => 'Estructura de participación',
                ),
                array(
                    'text' => '¿Quiénes participan en la toma de decisiones de este informe?',
                    'note' => 'Para entregar el análisis en formato adecuado y, si requiere, organizar presentaciones específicas.',
                    'type' => 'multi', 'req' => false, 'optional' => true,
                    'opts' => array(
                        'Equipo directivo interno',
                        'Comité de inversión',
                        'Consejo de administración',
                        'Asesores legales y fiscales externos',
                        'Asesores urbanísticos / arquitectos',
                        'Socios financieros (bancos, fondos)',
                        'Solo yo',
                        'Otros',
                    ),
                    'profileLabel' => 'Decisores que conocen el informe', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cuál es su horizonte temporal para la decisión final?',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Inminente — próximas 2-4 semanas',
                        'Próximos 1-3 meses',
                        'Próximos 3-6 meses',
                        'Próximo año',
                        'Sin urgencia — exploración estratégica',
                    ),
                    'profileLabel' => 'Plazo de decisión',
                ),
                array(
                    'text' => '¿Necesita un formato específico de entrega del informe?',
                    'note' => 'Podemos adaptar la entrega a las necesidades de su proceso interno.',
                    'type' => 'multi', 'req' => false, 'optional' => true,
                    'opts' => array(
                        'Informe estándar (PDF profesional)',
                        'Informe + presentación ejecutiva (PowerPoint)',
                        'Informe + reunión de presentación al comité',
                        'Informe en varios idiomas',
                        'Datos exportables (Excel, KMZ, GIS)',
                        'Acuerdo de confidencialidad (NDA) requerido',
                        'Mapeo cartográfico georreferenciado',
                    ),
                    'profileLabel' => 'Formato de entrega', 'profileFull' => true,
                ),
                array(
                    'text' => '¿Cómo prefiere recibir el presupuesto?',
                    'type' => 'single', 'req' => true,
                    'opts' => array(
                        'Por correo electrónico',
                        'Correo + videollamada para presentación',
                        'Reunión presencial en Marbella / Málaga / Alicante',
                        'Reunión presencial en su sede',
                    ),
                    'profileLabel' => 'Preferencia de entrega del presupuesto',
                ),
                array(
                    'text' => 'Información adicional relevante',
                    'note' => 'Cualquier detalle del proyecto, restricción, oportunidad o sensibilidad que deba conocer ROMVILL.',
                    'type' => 'textarea', 'key' => 'q17', 'ph' => 'Comentarios o información adicional...', 'req' => false, 'optional' => true,
                    'profileLabel' => 'Información adicional', 'profileFull' => true,
                ),
            ),
        ),
    ),
);

foreach ( array( 'en', 'de', 'fr', 'pt', 'ru' ) as $l ) {
    $config['lang'][ $l ] = $config['lang']['es'];
}

romvill_q_render( $config );
